# Generated by build.rs from packaging/homebrew/formula.rb.in. Do not edit by hand.
class Bracco < Formula
  desc "Fast fuzzy file picker: git-modified files first, respects .gitignore"
  homepage "https://github.com/rawnly/bracco"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.0/bracco-aarch64-apple-darwin.tar.xz"
      sha256 "42b49670c5adbeb380868a79952baa3cba49409768160f756b0dec4fefa39342"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.0/bracco-x86_64-apple-darwin.tar.xz"
      sha256 "e16bfb661ebc99e0c1535b987424125783fdaaf8aa7da101f5f2a81e7926a0b4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.0/bracco-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "82b05e9b5e87781d5435b50981e3973d6221e72c329d807dd8e7e05f74c3f43c"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.0/bracco-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "fbcec6a8ef37f25152cab96ca902eeeec7676e74ea771ca143474f011561b4fe"
    end
  end

  def install
    bin.install "bin/bracco"
    man1.install "share/man/man1/bracco.1"
    bash_completion.install "share/bash-completion/completions/bracco"
    zsh_completion.install "share/zsh/site-functions/_bracco"
    fish_completion.install "share/fish/vendor_completions.d/bracco.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bracco --version")
  end
end
