# Generated by build.rs from packaging/homebrew/formula.rb.in. Do not edit by hand.
class Bracco < Formula
  desc "Fast fuzzy file picker: git-modified files first, respects .gitignore"
  homepage "https://github.com/rawnly/bracco"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.3/bracco-aarch64-apple-darwin.tar.xz"
      sha256 "f60708a3d890b659cdb67fbea75faa260d3d188a5eebf1ccdd979e0029f26397"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.3/bracco-x86_64-apple-darwin.tar.xz"
      sha256 "54d837ddf7e83a631eb4b16c64f245268751143ed60833d8f9cd5cd879848841"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.3/bracco-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "32f4e84b045ae16a1be396589a9b0c4f92f6d64d77f0ba9c5771d2cc74be2ecc"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.3/bracco-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "ae53814d4502046486a918db2a5af6f40f49a911128213b9f77c99d5fa4207fa"
    end
  end

  def install
    bin.install "bin/bracco"
    man1.install "share/man/man1/bracco.1"
    bash_completion.install "share/bash-completion/completions/bracco"
    zsh_completion.install "share/zsh/site-functions/_bracco"
    fish_completion.install "share/fish/vendor_completions.d/bracco.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bracco --version")
  end
end
