# Generated by build.rs from packaging/homebrew/formula.rb.in. Do not edit by hand.
class Bracco < Formula
  desc "Fast fuzzy file picker: git-modified files first, respects .gitignore"
  homepage "https://github.com/rawnly/bracco"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.2/bracco-aarch64-apple-darwin.tar.xz"
      sha256 "9d39c5d0ef5b38d74a5ea29f9ada7cc483bb810fd9c73291cc40f6bc90593c0a"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.2/bracco-x86_64-apple-darwin.tar.xz"
      sha256 "4682d1e31c1a78b170bc013a710e83fa5b5ec0a80f268aae19367cce22b41d0d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.2/bracco-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "61ef6b9e8c3f1828fe1a211b664fbd4e5c64124625c3e7d2888f9d7e4dcc3fd5"
    end
    on_intel do
      url "https://github.com/rawnly/bracco/releases/download/v0.2.2/bracco-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "cb82c2ffb5eef4f5e931bb7df1004cebe63c8ccf320db3872642ae848bb72f7f"
    end
  end

  def install
    bin.install "bin/bracco"
    man1.install "share/man/man1/bracco.1"
    bash_completion.install "share/bash-completion/completions/bracco"
    zsh_completion.install "share/zsh/site-functions/_bracco"
    fish_completion.install "share/fish/vendor_completions.d/bracco.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bracco --version")
  end
end
