# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSelect < Formula
  desc "git checkout with ease"
  homepage "https://github.com/rawnly/git-select"
  version "0.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/rawnly/git-select/releases/download/0.0.4/git-select_0.0.4_Darwin_all.tar.gz"
    sha256 "2aff52898bfc6489ebf50f2ab5ee19c1fcdf81d8cfb5292ce39a6404aa4b49cc"

    def install
      bin.install "git-select"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnly/git-select/releases/download/0.0.4/git-select_0.0.4_Linux_arm64.tar.gz"
      sha256 "4daade7b1cc59eef11ddc337e39bf24526f50b7b55d7a6642542da36dfc5a735"

      def install
        bin.install "git-select"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rawnly/git-select/releases/download/0.0.4/git-select_0.0.4_Linux_x86_64.tar.gz"
      sha256 "8f4bcd676cac3c6ecbc318d59e84d88466ad469d8a121eb2fb859175206876f9"

      def install
        bin.install "git-select"
      end
    end
  end

  depends_on "git"
end
