# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAddCommit < Formula
  desc "Commit made easy"
  homepage "https://github.com/rawnly/git-add-commit"
  version "0.0.8"
  license "MIT"

  depends_on "git"

  on_macos do
    url "https://github.com/rawnly/git-add-commit/releases/download/0.0.8/GitAddCommit_0.0.8_Darwin_all.tar.gz"
    sha256 "694e33295aa896aace27927503f63ec0203fd09ae5348c96c3daedb1c8a707e7"

    def install
      bin.install "git-add-commit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.8/GitAddCommit_0.0.8_Linux_arm64.tar.gz"
      sha256 "745677448b71d6884b1f087484fa982ce19c3b78e1a1d92246a30142c70ad10a"

      def install
        bin.install "git-add-commit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.8/GitAddCommit_0.0.8_Linux_x86_64.tar.gz"
      sha256 "d891fa82b34bcc6c95cdcd9ca07cf0b65dea00b3eee8a06b83d08c20710e72df"

      def install
        bin.install "git-add-commit"
      end
    end
  end

  def caveats
    <<~EOS
      git-add-commit [message]
    EOS
  end
end
