# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSelect < Formula
  desc "git checkout with ease"
  homepage "https://github.com/rawnly/git-select"
  version "0.0.3"
  license "MIT"

  on_macos do
    url "https://github.com/rawnly/git-select/releases/download/0.0.3/git-select_0.0.3_Darwin_all.tar.gz"
    sha256 "cd7c18ce06e2775f606027aa6c259f750c5c6ffcf16817325e3a0f93ad9d1c8e"

    def install
      bin.install "git-select"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnly/git-select/releases/download/0.0.3/git-select_0.0.3_Linux_arm64.tar.gz"
      sha256 "11c04345623035d8fd7e731cdef8b0d85f19df6c3acfbdd989987ed354e23eb8"

      def install
        bin.install "git-select"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rawnly/git-select/releases/download/0.0.3/git-select_0.0.3_Linux_x86_64.tar.gz"
      sha256 "46f38d13870fd3f55fe58bf8eba25b2332e8a22265341713287221e57b2613e9"

      def install
        bin.install "git-select"
      end
    end
  end

  depends_on "git"
end
