# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAddCommit < Formula
  desc "Commit made easy"
  homepage "https://github.com/rawnly/git-add-commit"
  version "0.0.7"
  license "MIT"

  on_macos do
    url "https://github.com/rawnly/git-add-commit/releases/download/0.0.7/GitAddCommit_0.0.7_Darwin_all.tar.gz"
    sha256 "bc5ff9c691013f58836f87ebc7c656b10be808ce3009cfa74cdc442ca0420445"

    def install
      bin.install "git-add-commit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.7/GitAddCommit_0.0.7_Linux_arm64.tar.gz"
      sha256 "da454d1b89a66499e441f262f82c6977a8668c9405a895b1f70c7129e0e00dc2"

      def install
        bin.install "git-add-commit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.7/GitAddCommit_0.0.7_Linux_x86_64.tar.gz"
      sha256 "0c3765bd759b3b6362fe81a85ba271d77d78db15a17ac9568828fc1017f05ba6"

      def install
        bin.install "git-add-commit"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    git-add-commit [message]
  EOS
  end
end
