# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAddCommit < Formula
  desc "Commit made easy"
  homepage "https://github.com/rawnly/git-add-commit"
  version "0.0.5"
  license "MIT"

  on_macos do
    url "https://github.com/rawnly/git-add-commit/releases/download/0.0.5/GitAddCommit_0.0.5_Darwin_all.tar.gz"
    sha256 "a8408ca97854fae561845120c91de518aa4991f115eb136bb64a66e0286f9be6"

    def install
      bin.install "GitAddCommit_0.0.5"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.5/GitAddCommit_0.0.5_Linux_arm64.tar.gz"
      sha256 "faa3e48630483a0b23af85aafec3d90fd2948333328ec84f9f1282074da24ee5"

      def install
        bin.install "git-add-commit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rawnly/git-add-commit/releases/download/0.0.5/GitAddCommit_0.0.5_Linux_x86_64.tar.gz"
      sha256 "2b708666179b39352998f7b903e5cd59f0ff5eb79b77a34891f3fc8880127e78"

      def install
        bin.install "git-add-commit"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    git-add-commit [message]
  EOS
  end
end
